# Generated by Django 3.0 on 2022-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220117_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='categoria')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='categ',
            field=models.ManyToManyField(to='app.Categoria'),
        ),
    ]
